name: Concurrency Test

on: workflow_dispatch

jobs:
  concurrency_job:
    runs-on: ubuntu-latest
    concurrency:
      group: complex-task
      cancel-in-progress: true
    steps:
      - name: False complex job
        timeout-minutes: 1
        run: |
          echo "Complex job is running..."
          sleep 300s
          echo "Complex job has ended"
