name: Generate ASCII artwork

on: push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Create temp file
        run: echo "This is a temp file." >> tempfile.txt

      - name: Upload temp file
        uses: actions/upload-artifact@v4
        with:
          name: temp-file-artifact
          path: tempfile.txt

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Download temp file
        uses: actions/download-artifact@v4
        with:
          name: temp-file-artifact

      - name: Test file exists
        run: cat tempfile.txt
